### ISSUE TITLE
feat: Chain async pipe automatically to ngrxSelect pipe

### ISSUE THREAD

**Issue by jordanpowell88** [briebug/ngrx-smartish#31]
Users using the `ngrxSelect` pipe will always be using the `async` pipe. Would be nice to automatically append the async pipe when using `ngrxSelect`. 

```
<p>{{ selectors.getText | ngrxSelect | async }}</p>
```

would turn into:

```
<p>{{ selectors.getText | ngrxSelect }}</p>
```

**Comment by jordanpowell88** [comment]
@jrista Thoughts. on this?

**Comment by jrista** [comment]
Yeah, since we know they will always be observables, an argument can be made to automatically subscribe. Whether we could actually chain the `async` pipe or not, I am not sure...

Now, not everyone is necessarily going to use `async`...there are some third party libraries that allow you to subscribe in different ways. As a key example, RxAngular has the `push` directive which is a drop-in replacement for `async`. If someone wanted to use push, and leverage all of its benefits, if we auto-subscribe with `ngrxSelect` they wouldn't have that option.
